export const data = [
   {id:1, title:'Cien años de soledad', price:100, quantity:1, urlImage:'https://images.penguinrandomhouse.com/cover/9780525562443', descripcion: "1967. En Buenos Aires aparece la novela de un escritor colombiano de cuarenta años. No queda hoy lengua literaria a la que no haya sido traducida. \"Cien años de soledad\" no sólo cautiva a los lectores de cualquier condición: su impulso poderoso ha levantado las letras castellanas de todo un continente. Desvelar la magia de su prosa, acotar las arenas movedizas de su particular quehacer literario son tareas tan imposibles como dañinas; sí agradecerá el lector, en cambio, la aclaración de ciertas alusiones, la comprobación de la densidad que subyace a un texto aparentemente diáfano. No nos engañemos: son millones las páginas que han engendrado las de la novela, pero ante ella al lector no le queda otra actitud que la misma lectura devoradora y deslumbrada del último de los Aurelianos."},
   {id:2, title:'El Señor de los Anillos (Trilogía)', price:190, quantity:1, urlImage:'https://proassetspdlcom.cdnstatics2.com/usuaris/libros/fotos/358/original/portada_pack-trilogia-el-senor-de-los-anillos_j-r-r-tolkien_202206071544.jpg', descripcion: "Frodo Baggins recibe la misión de destruir el Anillo Único para evitar que Sauron domine la Tierra Media. Pero en su travesía no estará solo."},
   {id:3, title:'Cuentos de Barro', price:30, quantity:1, urlImage:'https://www.librosdelaballena.com/wp-content/uploads/2020/05/cuentos-barro-244x300.png', descripcion: "Colección de cuentos de Salarrué"},
   {id:4, title:'Tierra de Infancia', price:30, quantity:1, urlImage:'https://marketsvstg.blob.core.windows.net/marketsv/0011705_tierra-de-infancia_510.jpeg', descripcion: "Este libro no provocará ninguna polémica en los círculos literarios...No tiene tesis; es apenas un canto, una exaltación al folklore salvadoreño; un homenaje a las virtudes hogareñas de una familia representativa."},
   {id:5, title:'Harry Potter Pack', price:390, quantity:1, urlImage:'https://contentv2.tap-commerce.com/cover/large/9789878000473_1.jpg?id_com=1113', descripcion: "Colección de los 7 libros de la saga del mago más famoso de Hogwarts."},
   {id:6, title:'La Biblia Católica', price:15, quantity:1, urlImage:'https://ss365.liverpool.com.mx/xl/1116603710.jpg', descripcion: "Edición católica comentada de la Biblia, con líneas de tiempo y otros recursos para ayudar a que el lector conozca de cerca a Dios a través de su palabra."},
   {id:7, title:'El Hobbit', price:16, quantity:1, urlImage:'https://proassetspdlcom.cdnstatics2.com/usuaris/libros/fotos/348/original/portada_el-hobbit-ne_j-r-r-tolkien_202202140958.jpg', descripcion: 'La historia narra el viaje de un hobbit llamado Bilbo Bolsón, al que no le gustan las aventuras, a la Montaña Solitaria en busca del tesoro robado por el dragón Smaug años atrás. Todo empieza un inesperado día en el que Bilbo recibe la visita de Gandalf el Gris junto con 13 enanos, entre los que se cuenta a Thorin, Escudo-de-Roble, a cuya familia le fue robado el tesoro. Algunos de los hechos narrados en El Hobbit influirán en los acontecimientos posteriores de El Señor de los Anillos.'},
   {id:8, title:'Las Crónicas de Narnia: la saga completa', price:40, quantity:1, urlImage:'https://payhip.com/cdn-cgi/image/format=auto/https://pe56d.s3.amazonaws.com/o_1fnjrm6lo1lo8cs31n0d1mrt11utm.jpg',  descripcion: "Relata las aventuras en Narnia, una tierra de fantasía y magia creada por el autor y poblada por animales parlantes y otras criaturas mitológicas que se ven envueltas en la eterna lucha entre el bien y el mal."},
   {id:9, title:'Suma Teológica', price:50, quantity:1, urlImage:'https://pictures.abebooks.com/inventory/31251110367.jpg', descripcion: "Es un tratado de teología escrito entre 1265 y 1274 por el filósofo, teólogo escolástico y Doctor de la Iglesia, santo Tomás de Aquino (c. 1225–1274), durante los últimos años de su vida. Es un compendio de catecismo en forma de suma de todas las principales enseñanzas teológicas de la Iglesia católica, concebida como un manual para la educación teológica de los estudiantes de teología, incluidos los seminaristas y los laicos alfabetos, más que como obra apologética destinada a polemizar contra los no católicos. Presenta el razonamiento de casi todos los puntos de la teología cristiana en Occidente. "},
   {id:10, title:'La Isla del Tesoro', price:6, quantity:1, urlImage:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrkRuQVM0Voj0ySO45k92fI4MdfjO5Jf_5bw&s', descripcion: "La isla del tesoro narra una aventura de un tiempo lejano, en el que todavía había piratas y tesoros escondidos en islas desiertas. En esta novela, un mapa de una isla cae en manos del joven Jim Hawkins. El mapa indica el lugar donde el mayor pirata de todos los tiempos ha escondido su botín. Junto con un barón, un médico y una colorida tripulación, Jim parte en busca de la isla."},

];

